# Generated by Django 6.0.4 on 2026-05-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.IntegerField(primary_key=1, serialize=False)),
                ('uname', models.CharField(max_length=30)),
            ],
        ),
    ]
