# Generated by Django 6.0.4 on 2026-05-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=123, max_length=16),
            preserve_default=False,
        ),
    ]
