# Generated by Django 6.0.4 on 2026-05-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
